spring:
  datasource:
    db1:
      jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
      username: EJEMPLO
      password: ${PASS_DB1}
      driver-class-name: oracle.jdbc.OracleDriver

    db2:
      jdbc-url: jdbc:sqlserver://localhost\SQLEXPRESS;databaseName=CONTACTOS;encrypt=true;trustServerCertificate=true
      username: alfa
      password: ${PASS_DB2}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none

